
<style>
	th,td{ border:1px solid; }
	a{text-decoration: none; color:#fff; font-weight: bold;}
	a:hover{text-decoration: none;}
	.firstblk a{ padding:4px 8px; margin:0 20px; border: 1px solid #ed6502; background: #ffac47; cursor: pointer; }
	.firstblk{margin-bottom:20px; float:left; width:100%;}
	.secblock{float:left; width:100%;}
	.secblock a{color: #000;}
	.a-center{text-align:center;}
</style>

<?php 
$products = Mage::getModel('catalog/product')->getCollection();
$on=0; $off=0; $gm=0; $nomatch=0;

foreach ($products as $product) {
	$product = Mage::getModel('catalog/product')->load($product->getId());
	$mode = $product->getResource()->getAttribute('automode')->getFrontend()->getValue($product);	
	if($mode == "On"){
		$on++;
	}
	if($mode == "Off"){
		$off++;
	}
	if($mode == "Guardian Mode"){
		$gm++;
	}
	if($mode == "No match"){
		$nomatch++;
	}
}

$total = $on+$off+$gm+$nomatch; 

?>

<div class="content-header">
    <h3><?=$this->__('Home')?></h3>    
</div>

<div style="width:900px; margin:0 auto;">

	<div class="firstblk">
		<a href="<?php echo Mage::helper("adminhtml")->getUrl("web/adminhtml_rule/"); ?>">Rule Manager</a>
		<a href="<?php echo Mage::helper("adminhtml")->getUrl("web/adminhtml_web/"); ?>">Competitor Manager</a>
		<!-- <select>
			<option>Filter by competitor</option>
			<option>All</option>
			<option>Competitor1</option>
			<option>Competitor2</option>
			<option>Competitor3</option>
		</select> -->
	</div>
	<div class="secblock">
	<table style="border:2px solid #000;" width="100%">
		<tr>
			<th>Description</th>
			<th class="a-center">Products</th>
			<th class="a-center">Action</th>
		</tr>
		<tr>
			<td>Autopilot On</td>
			<td  class="a-center"><?php echo $on; ?></td>
			<td class="a-center"><a href="<?php echo Mage::helper("adminhtml")->getUrl("web/adminhtml_productlist/"); ?>"> Link </a></td>
		</tr>
		<tr>
			<td>Autopilot On Guardian Mode</td>
			<td class="a-center"><?php echo $gm; ?></td>
			<td class="a-center"><a href="<?php echo Mage::helper("adminhtml")->getUrl("web/adminhtml_productlist/"); ?>"> Link </a></td>
		</tr>
		<tr>
			<td>Autopilot Off</td>
			<td  class="a-center"><?php echo $off; ?></td>
			<td class="a-center"><a href="<?php echo Mage::helper("adminhtml")->getUrl("web/adminhtml_productlist/"); ?>"> Link </a></td>
		</tr>
		<!-- <tr>
			<td>Not Matched</td>
			<td class="a-center"><?php echo $nomatch; ?></td>
			<td class="a-center"><a href="<?php echo Mage::helper("adminhtml")->getUrl("web/adminhtml_productlist/"); ?>"> Link </a></td>
		</tr> -->
		<tr>
			<td><strong>Total</strong></td>
			<td  class="a-center"><?php echo $total; ?></td>
			<td class="a-center"><a href="<?php echo Mage::helper("adminhtml")->getUrl("web/adminhtml_productlist/"); ?>"> Link </a></td>
		</tr>
	</table>
</div>
</div> 