
<style>
	th,td{ border:1px solid; }
	a{text-decoration: none; color:#fff; font-weight: bold;}
	a:hover{text-decoration: none;}
	.firstblk a{ padding:4px 8px; margin:0 20px; border: 1px solid #ed6502; background: #ffac47; cursor: pointer; }
	.firstblk{margin-bottom:20px; float:left; width:100%;}
	.secblock{float:left; width:100%;}
	.secblock a{color: #000;}
</style>

<div class="content-header">
    <h3><?=$this->__('Home')?></h3>    
</div>

<div style="width:900px; margin:0 auto;">

	<div class="firstblk">
		<a href="<?php echo Mage::helper("adminhtml")->getUrl("web/adminhtml_rule/"); ?>">Rule Manager</a>
		<a href="<?php echo Mage::helper("adminhtml")->getUrl("web/adminhtml_web/"); ?>">Competitor Manager</a>
		<select>
			<option>Filter by competitor</option>
			<option>All</option>
			<option>Competitor1</option>
			<option>Competitor2</option>
			<option>Competitor3</option>
		</select>
	</div>
	<div class="secblock">
	<table style="border:2px solid #000;" width="100%">
		<tr>
			<th>Description</th>
			<th>Products</th>
			<th>Action</th>
		</tr>
		<tr>
			<td>Autopilot On</td>
			<td>2000</td>
			<td><a href="#"> Link </a></td>
		</tr>
		<tr>
			<td>Autopilot On Gaurdian Mode</td>
			<td>2000</td>
			<td><a href="#"> Link </a></td>
		</tr>
		<tr>
			<td>Autopilot Off</td>
			<td>2000</td>
			<td><a href="#"> Link </a></td>
		</tr>
		<tr>
			<td>Not Matched</td>
			<td>2000</td>
			<td><a href="#"> Link </a></td>
		</tr>
		<tr>
			<td>Total</td>
			<td>400</td>
			<td><a href="#"> Link </a></td>
		</tr>
	</table>
</div>
</div> 