<style>
table,td,th{ border: 1px solid #ccc; }
th{background: #ddd; text-align: center; color: #000; }
p.p-btn{text-align: right;clear: both; margin-bottom: 15px;}
.a-btn{text-decoration: none;padding: 8px; background: #ddd; border: 1px solid #ccc; color: #000; font-weight: bold;}
.a-btn:hover{text-decoration: none;}
</style>
<?php 

	$resource = Mage::getSingleton('core/resource');
	$readConnection = $resource->getConnection('core_read');
	$writeConnection = $resource->getConnection('core_write');
	
?>

<div style="float:left; width:100%;">

<div style="width:600px; margin:0 auto;">
	<h1>Rule Manager</h1>
	<p class="p-btn"><a href="<?php  //echo Mage::helper("adminhtml")->getUrl("web/adminhtml_rule/addruleform"); ?>" class="a-btn">Add Rule</a></p>
	<div>
		<table style="border:2px solid #ccc; width:100%;margin-bottom:20px;">
			<tr>
				<th>Name</th>
				<th>Description</th>
				<th>Action</th>
			</tr>
			
			<tr>
				<td>Rule one</td>
				<td>Rule description</td>
				<td><a href="">Edit</a> <span style="margin:0 5px;">|</span><a href="">Delete</a></td>
			</tr>
			<tr>
				<td>Rule one</td>
				<td>Rule description</td>
				<td><a href="">Edit</a> <span style="margin:0 5px;">|</span><a href="">Delete</a></td>
			</tr>
		</table>
	</div>
</div>


</div>